### ISSUE TITLE
cant link world

### ISSUE THREAD

**Issue by GeoLei2u** [MylesAndMore/Tumble#13]
when i try and link my world it says "An internal error occurred when trying to perform this command"

**Comment by GeoLei2u** [comment]
actually every command does that

**Comment by MylesAndMore** [comment]
Sorry, but I need some more information to help. Do you have access to the server's console? If so, try running a command and send any console output here.
If not, any extra information (server type, other plugins, etc.) can help.

**Comment by GeoLei2u** [comment]
Yes, I am running it on my pc using server.jar on 1.20.1. I can send the full error when I run it though console.

**Comment by GeoLei2u** [comment]
![image](https://github.com/MylesAndMore/Tumble/assets/89065592/bbf48814-789d-4269-bdb6-731e92746b57)

**Comment by GeoLei2u** [comment]
multiverse commands work so its just tumble plugin thats broken

**Comment by GeoLei2u** [comment]
do you have a fix yet

**Comment by GeoLei2u** [comment]
I found a fix, I used paper instead of spigot and it works
