### ISSUE TITLE
What permissions do I need to give for players to run /tumble:start?

### ISSUE THREAD

**Issue by ImmortalBeastYT** [MylesAndMore/Tumble#4]

**Comment by MylesAndMore** [comment]
Whoops, it looks like there was a slight bug in the naming of the permission nodes.
I fixed it in the [latest version](https://github.com/MylesAndMore/tumble/releases)--the permission is now ```tumble.start``` as correctly described in the readme.

Alternatively, the node ```start``` will probably work on your older version, but I still suggest that you update anyway.

Hope this solves your issue!
