### ISSUE TITLE
Tumble World Download

### ISSUE THREAD

**Issue by TheBlindBat** [MylesAndMore/Tumble#6]
So, I am trying to set this whole thing up and I think I understand how to use the plugin but do I need to provide a tumble world or will the plugin deal with that?

**Comment by MylesAndMore** [comment]
Unfortunately I’m not able to redistribute any worlds with the plugin so you will have to provide your own world. I did however provide a download link to the original game and lobby worlds that you can use in [my guide](https://github.com/MylesAndMore/tumble/blob/main/og-guide.md).

Let me know if you have any other issues setting up the plugin!

**Comment by TheBlindBat** [comment]
Lol, I figured it out right after I sent that. FYI your arena download link is just a download for the most resent lobby.

**Comment by MylesAndMore** [comment]
Odd, thanks for letting me know! I think I fixed it.
